In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

df = pd.read_csv("/Users/premthatikonda/Downloads/FeatureEnggAndMLOPs/data/raw/Unit-02/feature_creation_data.csv")
df.head()

,student_id,study_hours,attendance_pct,prev_score,doubt_sessions,final_score
0,3001,7.0,56.5,48.6,1,26.8
1,3002,4.6,68.0,74.6,2,27.8
2,3003,7.5,97.6,67.2,3,26.7
3,3004,6.1,71.0,51.1,6,32.5
4,3005,2.1,47.6,52.6,2,25.7

In [2]:
df["study_x_attendance"] = df["study_hours"] * df["attendance_pct"]
df[["study_hours", "attendance_pct", "study_x_attendance"]].head()

   study_hours  attendance_pct  study_x_attendance
0          7.0            56.5              395.50
1          4.6            68.0              312.80
2          7.5            97.6              732.00
3          6.1            71.0              433.10
4          2.1            47.6               99.96